//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMR.WebAPI.ehr.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimCondition
    {
        public int Id { get; set; }
        public string EPSDT { get; set; }
        public string Anesthesia { get; set; }
        public string Conditions { get; set; }
        public string Vision { get; set; }
    }
}
