//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMR.WebAPI.ehr.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimLineDate
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Prescription { get; set; }
        public Nullable<System.DateTime> Certification { get; set; }
        public Nullable<System.DateTime> BeginTherapy { get; set; }
        public Nullable<System.DateTime> LastCertification { get; set; }
        public Nullable<System.DateTime> LastSeen { get; set; }
        public Nullable<System.DateTime> Test { get; set; }
        public Nullable<System.DateTime> Shipped { get; set; }
        public Nullable<System.DateTime> LastXRay { get; set; }
        public Nullable<System.DateTime> InitialTreatment { get; set; }
        public string SystemNoteKey { get; set; }
        public Nullable<System.DateTime> ServiceFrom { get; set; }
        public Nullable<System.DateTime> ServiceTo { get; set; }
    
        public virtual ClaimLine ClaimLine { get; set; }
    }
}
