//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMR.WebAPI.ehr.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimLineReference
    {
        public int Id { get; set; }
        public string Repriced { get; set; }
        public string AdjustedRepriced { get; set; }
        public string Prior { get; set; }
        public string PriorIdentifier { get; set; }
        public string PriorOtherPayer { get; set; }
        public string ControlNumber { get; set; }
        public string Mammography { get; set; }
        public string CLIA { get; set; }
        public string CLIAFacility { get; set; }
        public string Immunization { get; set; }
        public string Referral { get; set; }
        public string ReferralIdentifier { get; set; }
        public string ReferralOtherPayer { get; set; }
        public string SystemNoteKey { get; set; }
    
        public virtual ClaimLine ClaimLine { get; set; }
    }
}
