//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMR.WebAPI.ehr.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimReference
    {
        public int Id { get; set; }
        public string AuthorizationException { get; set; }
        public string MandatoryMedicare { get; set; }
        public string Mammography { get; set; }
        public string Referral { get; set; }
        public string Prior { get; set; }
        public string ClaimControl { get; set; }
        public string Repriced { get; set; }
        public string AdjustedRepriced { get; set; }
        public string InvestigationalDevice { get; set; }
        public string Transmission { get; set; }
        public string MedicalRecord { get; set; }
        public string Demonstration { get; set; }
        public string CarePlanOversight { get; set; }
        public string CLIA { get; set; }
    }
}
