//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMR.WebAPI.ehr.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimAccident
    {
        public int Id { get; set; }
        public string Causes { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
