//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMR.WebAPI.ehr.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimLineSupplemental
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClaimLineSupplemental()
        {
            this.SalesTaxAmount = 0m;
            this.PostageAmount = 0m;
            this.PurchaseAmount = 0m;
            this.ObsAnesUnits = 0;
        }
    
        public int Id { get; set; }
        public Nullable<decimal> SalesTaxAmount { get; set; }
        public Nullable<decimal> PostageAmount { get; set; }
        public string FileInfo { get; set; }
        public string NoteCode { get; set; }
        public string NoteDescription { get; set; }
        public string ThirdPartyCode { get; set; }
        public string ThirdPartyDescription { get; set; }
        public string PurchaseCode { get; set; }
        public Nullable<decimal> PurchaseAmount { get; set; }
        public string RejectCode { get; set; }
        public string ComplianceCode { get; set; }
        public string ExceptionCode { get; set; }
        public string HospiceCode { get; set; }
        public Nullable<int> ObsAnesUnits { get; set; }
        public string SystemNoteKey { get; set; }
    
        public virtual ClaimLine ClaimLine { get; set; }
    }
}
