//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMR.WebAPI.ehr.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimLineDMERC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClaimLineDMERC()
        {
            this.DMERC_Response = "N";
        }
    
        public int Id { get; set; }
        public string DMERC_Response { get; set; }
        public string DMERC_Code { get; set; }
        public string DMERC_Code2 { get; set; }
        public string SystemNoteKey { get; set; }
    }
}
