//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMR.WebAPI.ehr.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimRepricing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClaimRepricing()
        {
            this.AllowedAmount = 0m;
            this.SavingAmount = 0m;
            this.AmbulatoryAmount = 0m;
        }
    
        public int Id { get; set; }
        public string Methodology { get; set; }
        public Nullable<decimal> AllowedAmount { get; set; }
        public Nullable<decimal> SavingAmount { get; set; }
        public string OrgIdentifier { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string AmbulatoryGroup { get; set; }
        public Nullable<decimal> AmbulatoryAmount { get; set; }
        public string RejectReason { get; set; }
        public string PolicyCompliance { get; set; }
        public string Exception { get; set; }
    }
}
