//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMR.WebAPI.ehr.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facility
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Facility()
        {
            this.BillUnder = "1";
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string SystemNoteKey { get; set; }
        public string Extension { get; set; }
        public string NPI { get; set; }
        public string TaxId { get; set; }
        public string Address_1 { get; set; }
        public string Address_2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string PaytoAddress_1 { get; set; }
        public string PaytoAddress_2 { get; set; }
        public string PaytoCity { get; set; }
        public string PaytoState { get; set; }
        public string PaytoZip { get; set; }
        public string ContactName { get; set; }
        public string BillUnder { get; set; }
    }
}
