//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMR.WebAPI.ehr.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.IsDeceased = false;
            this.IsPregnant = false;
            this.Gender = "M";
            this.Relationship = "18";
        }
    
        public int Id { get; set; }
        public string AccountNumber { get; set; }
        public string SystemNoteKey { get; set; }
        public Nullable<bool> IsDeceased { get; set; }
        public Nullable<System.DateTime> DateOfDeath { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<bool> IsPregnant { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Notes { get; set; }
        public string Suffix { get; set; }
        public string Address_1 { get; set; }
        public string Address_2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Relationship { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    }
}
