//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMR.WebAPI.ehr.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.AmountTotal = 0m;
            this.AmountPayment = 0m;
            this.AmountDeductible = 0m;
            this.PaymentLines = new HashSet<PaymentLine>();
        }
    
        public int Id { get; set; }
        public string SystemNoteKey { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Notes { get; set; }
        public decimal AmountTotal { get; set; }
        public decimal AmountPayment { get; set; }
        public decimal AmountCopay { get; set; }
        public decimal AmountDeductible { get; set; }
        public decimal AmountBalance { get; set; }
    
        public virtual ErrorCode ErrorCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentLine> PaymentLines { get; set; }
    }
}
