//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMR.WebAPI.ehr.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentLine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentLine()
        {
            this.AmountPayment = 0m;
            this.AmountDeductible = 0m;
        }
    
        public int Id { get; set; }
        public string SystemNoteKey { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> ClaimLineId { get; set; }
        public Nullable<decimal> AmountPayment { get; set; }
        public Nullable<decimal> AmountCopay { get; set; }
        public Nullable<decimal> AmountDeductible { get; set; }
        public Nullable<int> PaymentId { get; set; }
    }
}
