//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMR.WebAPI.ehr.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Provider()
        {
            this.IsCompany = false;
            this.Credential = "MD";
            this.IsReferrer = false;
            this.Addresses = new HashSet<Address>();
            this.Providers = new HashSet<Provider>();
        }
    
        public int Id { get; set; }
        public string EIN { get; set; }
        public string SSN { get; set; }
        public string NPI { get; set; }
        public string License { get; set; }
        public string UPIN { get; set; }
        public string SystemNoteKey { get; set; }
        public Nullable<int> TaxonomyCodeId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Suffix { get; set; }
        public string Phone_1 { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string Phone_2 { get; set; }
        public string Address_1 { get; set; }
        public string Address_2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public bool IsCompany { get; set; }
        public string Credential { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public bool IsReferrer { get; set; }
    
        public virtual TaxonomyCode TaxonomyCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Address> Addresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Provider> Providers { get; set; }
    }
}
