//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMR.WebAPI.ehr.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscriber
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subscriber()
        {
            this.Gender = "M";
            this.IsDeceased = false;
            this.IsPregnant = false;
            this.Addresses = new HashSet<Address>();
            this.Patients = new HashSet<Patient>();
        }
    
        public int Id { get; set; }
        public string SystemNoteKey { get; set; }
        public string PrimaryMemberID { get; set; }
        public string SecondaryMemberID { get; set; }
        public string PrimaryExpiryDate { get; set; }
        public string SecondaryExpiryDate { get; set; }
        public Nullable<int> PrimaryPayerId { get; set; }
        public Nullable<int> SecondaryPayerId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string Phone_1 { get; set; }
        public string Phone_2 { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string Notes { get; set; }
        public string Suffix { get; set; }
        public string Address_1 { get; set; }
        public string Address_2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string GroupName { get; set; }
        public string GroupNumber { get; set; }
        public string PrimaryPayerType { get; set; }
        public string SecondaryPayerType { get; set; }
        public Nullable<bool> IsDeceased { get; set; }
        public Nullable<System.DateTime> DateOfDeath { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<bool> IsPregnant { get; set; }
        public string SSN { get; set; }
        public Nullable<int> PrimaryInsurerId { get; set; }
        public Nullable<int> SecondaryInsurerId { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        public virtual Payer PrimaryPayer { get; set; }
        public virtual Payer SecondaryPayer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Address> Addresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patient> Patients { get; set; }
    }
}
