//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMR.WebAPI.ehr.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxonomyCode
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Grouping { get; set; }
        public string Classification { get; set; }
        public string Specialization { get; set; }
        public string Definition { get; set; }
        public string Notes { get; set; }
    }
}
