//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMR.WebAPI.ehr.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPreference
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserPreference()
        {
            this.UserId = -1;
            this.AccountId = -1;
        }
    
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public string SystemNoteKey { get; set; }
        public Nullable<int> RenderingProviderId { get; set; }
        public Nullable<int> BillingProviderId { get; set; }
        public Nullable<int> FacilityId { get; set; }
        public Nullable<int> PlaceOfServiceId { get; set; }
    }
}
